import { Project, StudioAward } from './types';

export const PROJECTS_DATA: Project[] = [
  {
    id: 'chronicles-of-light',
    title: 'Chronicles of Light',
    client: 'Maison Hermès',
    year: '2025',
    category: 'Digital Scenography & WebGL',
    tagline: 'An ephemeral virtual sanctuary exploring the tactile heritage of silk and luminescence.',
    description: 'An ethereal multi-sensory interactive journey traversing handcrafted bas-relief digital textiles, fluid simulation, and bespoke ambient audio. Created as the centerpiece for the international digital vernissage.',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1400&q=80',
    detailImages: [
      'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    ],
    awards: ['Awwwards Site of the Year Nominee', 'FWA of the Month', 'Cannes Lions Silver (Digital Craft)'],
    role: 'Creative Direction, WebGL Engineering, Sound Design',
    deliverables: ['Real-time 3D Scenography', 'Generative Audio Engine', 'Interactive Campaign Portal'],
    accentColor: '#D97706',
    featured: true,
    stats: [
      { label: 'Avg. Interaction Time', value: '4m 38s' },
      { label: 'Global Visitors', value: '1.4M+' },
      { label: 'Frame Rate', value: '60 FPS Ultra' },
    ],
  },
  {
    id: 'acoustic-monolith',
    title: 'Acoustic Monolith',
    client: 'Bang & Olufsen',
    year: '2024',
    category: 'Spatial Audio & Interactive Sculpture',
    tagline: 'Sculpting high-fidelity acoustic resonances into visible physical frequencies.',
    description: 'A monolithic 3D product visualizer that translates acoustic waveforms into tactile, physical displacement surfaces in real time. Users manipulate sound waves to explore precision acoustic engineering.',
    coverImage: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1400&q=80',
    detailImages: [
      'https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    ],
    awards: ['Awwwards Site of the Month', 'FWA of the Day', 'Red Dot Best of the Best'],
    role: 'Technical Architecture, 3D Shaders, Spatial Audio',
    deliverables: ['Interactive Product Journey', 'Custom WebAudio Synthesizer', 'Global Launch Experience'],
    accentColor: '#4F46E5',
    featured: true,
    stats: [
      { label: 'Sound Waves Rendered', value: '24 kHz' },
      { label: 'Engagement Rate', value: '+340%' },
      { label: 'Global Markets', value: '28 Countries' },
    ],
  },
  {
    id: 'metamorphosis-botanica',
    title: 'Metamorphosis Botanica',
    client: 'Cartier Haute Joaillerie',
    year: '2024',
    category: 'Immersive Editorial & 3D Archive',
    tagline: 'Bridging botanical morphology and high-jewelry craftsmanship through living digital stone.',
    description: 'An interactive botanical atlas showcasing rare gemstones sculpted as floral reliefs and blooming micro-mechanisms. Microscopic zoom capabilities allow collectors to inspect facets at 100x resolution.',
    coverImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1400&q=80',
    detailImages: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1576016770958-e0b2dc9d7ffb?auto=format&fit=crop&w=1200&q=80',
    ],
    awards: ['FWA Site of the Month', 'D&AD Wood Pencil', 'Awwwards Developer Award'],
    role: 'Lead Interactive Design, Custom PBR Pipeline, Micro-UI',
    deliverables: ['Hyper-detailed 3D Gem Viewer', 'Curated Editorial Narrative', 'VIP Client Portal'],
    accentColor: '#059669',
    featured: true,
    stats: [
      { label: 'Precision Zoom', value: '100x Macro' },
      { label: 'High Jewelry Orders', value: 'Private VIP' },
      { label: 'Awwwards Score', value: '8.94 / 10' },
    ],
  },
  {
    id: 'solaris-kinetic',
    title: 'Solaris Kinetic',
    client: 'Polestar Automotive',
    year: '2024',
    category: 'Real-time Kinetic Configurator',
    tagline: 'Exploring aerodynamic form through mathematical air currents and solar light paths.',
    description: 'A minimalist, architectural vehicle configurator rendering photorealistic aerodynamic slipstreams and sculpted carbon fiber surfaces with zero loading latency.',
    coverImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=80',
    detailImages: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80',
    ],
    awards: ['Awwwards Site of the Day', 'FWA of the Day'],
    role: 'WebGL Engineering, Performance Optimization',
    deliverables: ['Real-time 3D Configurator', 'Custom Raymarched Reflections', 'Global Dealership App'],
    accentColor: '#2563EB',
    featured: false,
    stats: [
      { label: 'Load Time', value: '< 1.2s' },
      { label: 'Build Configurations', value: '45,000+' },
    ],
  },
  {
    id: 'terra-incognita',
    title: 'Terra Incognita',
    client: 'Centre Pompidou',
    year: '2023',
    category: 'Virtual Museum & Spatial Exhibition',
    tagline: 'An infinite architectural labyrinth of contemporary digital sculptures.',
    description: 'An interactive virtual museum retrospective celebrating avant-garde architectural bas-relief sculptures and spatial soundscapes from emerging international artists.',
    coverImage: 'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=1400&q=80',
    detailImages: [
      'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=1200&q=80',
    ],
    awards: ['Awwwards Best UI/UX', 'European Design Award Gold'],
    role: 'Exhibition Curation, Virtual Architecture, WebGL Experience',
    deliverables: ['Virtual Pavilion', 'Spatial Audio Experience', 'Exhibition Catalog'],
    accentColor: '#E11D48',
    featured: false,
    stats: [
      { label: 'Exhibits Rendered', value: '64 Pieces' },
      { label: 'Virtual Visitors', value: '820K+' },
    ],
  },
  {
    id: 'silk-strata',
    title: 'Silk & Strata',
    client: 'Yves Saint Laurent Beauté',
    year: '2023',
    category: 'Digital Runway & Couture Experience',
    tagline: 'Deconstructing texture, fabric tension, and couture materiality in real time.',
    description: 'A sensory digital campaign celebrating couture texture through ultra-high definition cloth simulations that react dynamically to touch, cursor glide, and sound vibrations.',
    coverImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1400&q=80',
    detailImages: [
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80',
    ],
    awards: ['FWA of the Day', 'Awwwards Honorable Mention'],
    role: 'Creative Direction, Cloth Physics Simulation',
    deliverables: ['Digital Campaign Site', 'Interactive Fabric Sandbox'],
    accentColor: '#9333EA',
    featured: false,
    stats: [
      { label: 'Physical Fibers Simulated', value: '120K' },
      { label: 'Campaign Reach', value: '4.2M' },
    ],
  },
];

export const STUDIO_AWARDS: StudioAward[] = [
  { year: '2025', title: 'Site of the Year Nominee', organization: 'Awwwards', project: 'Chronicles of Light' },
  { year: '2025', title: 'FWA of the Month', organization: 'FWA Awards', project: 'Chronicles of Light' },
  { year: '2024', title: 'Site of the Month', organization: 'Awwwards', project: 'Acoustic Monolith' },
  { year: '2024', title: 'Cannes Lions Silver (Digital Craft)', organization: 'Cannes Lions', project: 'Maison Hermès' },
  { year: '2024', title: 'Studio of the Year Finalist', organization: 'Awwwards', project: 'Immersive Garden' },
  { year: '2023', title: 'Best Digital Scenography', organization: 'D&AD Awards', project: 'Metamorphosis Botanica' },
  { year: '2023', title: 'European Design Gold', organization: 'EDA Awards', project: 'Centre Pompidou' },
];

export const CLIENT_LIST = [
  'Hermès Paris',
  'Bang & Olufsen',
  'Cartier',
  'Polestar',
  'Centre Pompidou',
  'Yves Saint Laurent',
  'Bottega Veneta',
  'Rimowa',
  'Audemars Piguet',
  'MoMA New York',
  'Leica Camera',
  'Bowers & Wilkins',
];
