import { CategoryInfo, ContactAddon, PhotographyRating } from './types';

export const PHOTOGRAPHY_CATEGORIES: CategoryInfo[] = [
  {
    id: 'portrait',
    name: 'Portrait & Headshots',
    tagline: 'Studio lighting, creative bokeh & natural character portraits',
    basePrice: 14999,
    popular: true,
  },
  {
    id: 'wedding',
    name: 'Weddings & Elopements',
    tagline: 'Timeless cinematic coverage & intimate candid emotion',
    basePrice: 89999,
    popular: true,
  },
  {
    id: 'editorial',
    name: 'Fashion & Editorial',
    tagline: 'Avant-garde styling, magazine color science & high-fashion look',
    basePrice: 34999,
  },
  {
    id: 'commercial',
    name: 'Product & Commercial',
    tagline: 'Crisp commercial assets for lookbooks, ads & luxury brands',
    basePrice: 44999,
  },
  {
    id: 'event',
    name: 'Private & Corporate Events',
    tagline: 'Dynamic documentary coverage with zero disruption',
    basePrice: 24999,
  },
  {
    id: 'drone',
    name: 'Aerial & Architecture',
    tagline: 'DGCA-compliant 4K raw drone sweeps & structural perspectives',
    basePrice: 19999,
  },
];

export const CONTACT_ADDONS: ContactAddon[] = [
  {
    id: 'drone_footage',
    name: '4K Aerial Drone Coverage',
    price: 12000,
    description: 'High-resolution bird-eye sweeps and cinematic establishing shots',
  },
  {
    id: 'second_shooter',
    name: 'Secondary Lead Photographer',
    price: 16500,
    description: 'Double the angles, synchronized second perspective and wider candid coverage',
  },
  {
    id: 'rush_delivery',
    name: '48-Hour Express Color Grading',
    price: 7500,
    description: 'Expedited editorial post-processing and early private web gallery',
  },
  {
    id: 'fine_art_album',
    name: 'Handcrafted Linen Fine Art Book',
    price: 14000,
    description: 'Custom embossed 30-page archival cotton rag photography album',
  },
];

export const INITIAL_REVIEWS: PhotographyRating[] = [
  {
    id: 'rev-1',
    clientName: 'Elena Rostova',
    roleOrTag: 'Bride & Art Director',
    category: 'wedding',
    overallRating: 5,
    photoQualityRating: 5,
    lightingCompositionRating: 5,
    professionalismRating: 5,
    turnaroundTimeRating: 5,
    title: 'Breathtaking golden-hour light and flawless color rendition',
    reviewText:
      'Working with the studio for our coastal wedding was an absolute revelation. The way natural sunlight was framed through the trees captured our intimacy without feeling posed. Guests were stunned when our sneak peek gallery arrived in under 48 hours!',
    favoriteDeliverable: 'Coastal cliffside sunset vows & film grain black-and-whites',
    wouldRecommend: true,
    date: 'August 24, 2026',
    verifiedClient: true,
    helpfulCount: 34,
  },
  {
    id: 'rev-2',
    clientName: 'Marcus Vance',
    roleOrTag: 'Creative Director at ORA Studios',
    category: 'commercial',
    overallRating: 5,
    photoQualityRating: 5,
    lightingCompositionRating: 5,
    professionalismRating: 5,
    turnaroundTimeRating: 4,
    title: 'Top-tier commercial precision & studio lighting mastery',
    reviewText:
      'We booked a 2-day product editorial for our new luxury collection. The macro detail, specular highlight control, and calibrated neutral color tones saved our post-production team dozens of retouching hours. Exemplary technical craft.',
    favoriteDeliverable: 'Polarized macro product shots and moody dark-slate backdrop campaign',
    wouldRecommend: true,
    date: 'July 18, 2026',
    verifiedClient: true,
    helpfulCount: 21,
  },
  {
    id: 'rev-3',
    clientName: 'Chloe Dupont',
    roleOrTag: 'Independent Fashion Designer',
    category: 'editorial',
    overallRating: 5,
    photoQualityRating: 5,
    lightingCompositionRating: 5,
    professionalismRating: 5,
    turnaroundTimeRating: 5,
    title: 'Captures the soul of textiles with museum-grade aesthetics',
    reviewText:
      'The photographer’s eye for silhouette and motion gave our spring lookbook an authentic editorial edge. Models felt completely relaxed and directed with clear vision. Truly exceptional photography.',
    favoriteDeliverable: 'Monochrome architectural outdoor portrait series',
    wouldRecommend: true,
    date: 'June 09, 2026',
    verifiedClient: true,
    helpfulCount: 19,
  },
  {
    id: 'rev-4',
    clientName: 'Dr. Julian Thorne',
    roleOrTag: 'Architectural Consultant',
    category: 'drone',
    overallRating: 5,
    photoQualityRating: 5,
    lightingCompositionRating: 4,
    professionalismRating: 5,
    turnaroundTimeRating: 5,
    title: 'Flawless structural symmetry and high dynamic range',
    reviewText:
      'Aerial survey photography was required for our glass pavilion portfolio. The horizontal alignment, distortion-free optics, and twilight exposure bracket yielded breathtaking results.',
    favoriteDeliverable: 'Blue-hour drone perspective overlooking the courtyard',
    wouldRecommend: true,
    date: 'May 28, 2026',
    verifiedClient: true,
    helpfulCount: 14,
  },
  {
    id: 'rev-5',
    clientName: 'Sienna & Noah Campbell',
    roleOrTag: 'Couple Portrait Session',
    category: 'portrait',
    overallRating: 4.8,
    photoQualityRating: 5,
    lightingCompositionRating: 5,
    professionalismRating: 5,
    turnaroundTimeRating: 4.5,
    title: 'Felt like effortless friends capturing magic',
    reviewText:
      'We were anxious in front of studio cameras, but the subtle lighting and warm coaching put us right at ease within five minutes. The final portraits look like stills from a modern cinema film.',
    favoriteDeliverable: 'Warm 85mm prime portraits with soft natural falloff',
    wouldRecommend: true,
    date: 'April 14, 2026',
    verifiedClient: true,
    helpfulCount: 12,
  },
];
