import { SiteConfig, TypographyConfig, ImageCustomStyleConfig } from './types';

export const DEFAULT_TYPOGRAPHY: TypographyConfig = {
  fontFamily: 'serif',
  fontWeight: '400',
  fontSizeScale: 1.0,
  letterSpacing: 'normal',
  textTransform: 'uppercase',
  textEffect: 'none',
  color: '#151515',
};

export const DEFAULT_IMAGE_STYLE: ImageCustomStyleConfig = {
  url: '',
  scale: 1.0,
  aspectRatio: 'natural',
  borderRadius: 0,
  contrast: 100,
  brightness: 100,
  saturation: 100,
  blur: 0,
  sepia: 0,
  grayscale: false,
};

export const DEFAULT_SITE_CONFIG: SiteConfig = {
  effects: {
    grainOpacity: 0.035,
    grainSpeed: 12,
    contrast: 104,
    brightness: 100,
    saturation: 100,
    sepia: 0,
    vignetteIntensity: 0.16,
    fogOpacity: 0.015,
    glassBlur: 12,
    accentColor: '#111111',
    ambientTint: '#EBE7E1',
  },
  home: {
    hero: {
      monographTitle: 'DREAMSCAPES',
      volumeTag: 'DREAMSCAPES MONOGRAPH VOL. 01',
      publishedDate: 'EXHIBITION PUBLISHED SPRING 2026',
      locationArchive: 'KYOTO — REYKJAVIK — TOKYO',
      archiveLabel: 'STILL STUDIO ARCHIVE',
      headlineSecondary: 'ARCHITECTURAL MONOGRAPHS & ATMOSPHERIC LIGHT PHENOMENA',
      plate01Title: 'PLATE 01.0 — KYOTO MONOLITH',
      plate01Camera: 'HASSELBLAD 120MM',
      plate01Image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=2600&q=98',
      plate02Title: 'Concrete Sanctuary Void',
      plate02Location: 'TOKYO, JAPAN — 2025',
      plate02Image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2000&q=98',
      ctaButtonText: 'CONTACT & REVIEW',
      ctaButtonLink: '/contact-reviews',
      scrollPrompt: 'SCROLL TO DISCOVER',
      titleTypography: {
        fontFamily: 'serif',
        fontWeight: '400',
        fontSizeScale: 1.0,
        letterSpacing: 'normal',
        textTransform: 'uppercase',
        textEffect: 'none',
        color: '#151515',
      },
      headlineTypography: {
        fontFamily: 'sans',
        fontWeight: '500',
        fontSizeScale: 1.0,
        letterSpacing: 'wide',
        textTransform: 'uppercase',
        textEffect: 'none',
        color: '#444444',
      },
      plate01Style: {
        scale: 1.0,
        aspectRatio: 'natural',
        borderRadius: 0,
        contrast: 100,
        brightness: 100,
        saturation: 100,
        blur: 0,
        sepia: 0,
        grayscale: false,
      },
      plate02Style: {
        scale: 1.0,
        aspectRatio: 'natural',
        borderRadius: 0,
        contrast: 100,
        brightness: 100,
        saturation: 100,
        blur: 0,
        sepia: 0,
        grayscale: false,
      },
    },
    curatorial: {
      eyebrowNumber: '01',
      eyebrowTitle: 'CURATORIAL OVERVIEW',
      eyebrowSub: 'DREAMSCAPES ARCHIVE · STILL STUDIO',
      headlineWords: ['THE', 'SILENCE', 'OF', 'MONUMENTAL', 'FORMS'],
      paragraph1:
        'DREAMSCAPES documents the tension between permanent brutalist geometry and ephemeral meteorological phenomena. Captured across six seasons between the highland plateaus of Reykjavik and the concrete sanctuaries of Kyoto and Tokyo.',
      paragraph2:
        'Each exposure prioritizes natural atmospheric gradation over artificial correction. Photographed on medium-format analog film and ultra-high dynamic range digital sensors, the collection isolates the tactile silence that occurs when human form withdraws from monumental space.',
      chronology: '2024 — 2026',
      medium: 'ANALOG & DIGITAL',
      fieldStations: 'KYOTO · REYKJAVIK',
      curator: 'STILL STUDIO',
      headlineTypography: {
        fontFamily: 'editorial',
        fontWeight: '300',
        fontSizeScale: 1.0,
        letterSpacing: 'tight',
        textTransform: 'uppercase',
        textEffect: 'none',
        color: '#151515',
      },
      plateStyle: {
        scale: 1.0,
        aspectRatio: 'natural',
        borderRadius: 0,
        contrast: 100,
        brightness: 100,
        saturation: 100,
        blur: 0,
        sepia: 0,
        grayscale: false,
      },
    },
    nextMonograph: {
      volumeTag: 'MONOGRAPH VOL. 02',
      title: 'BLUEYARD',
      launchDate: 'OCTOBER 2026',
      teaserParagraph:
        'An uncompromising deep dive into maritime brutalism and salt-encrusted concrete bastions along the sub-Arctic coastline of northern Norway and Iceland.',
      bannerImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&w=2600&q=98',
      ctaText: 'EXPLORE CASE STUDY',
      titleTypography: {
        fontFamily: 'serif',
        fontWeight: '300',
        fontSizeScale: 1.0,
        letterSpacing: 'wide',
        textTransform: 'uppercase',
        textEffect: 'none',
        color: '#151515',
      },
      bannerStyle: {
        scale: 1.0,
        aspectRatio: 'natural',
        borderRadius: 0,
        contrast: 100,
        brightness: 100,
        saturation: 100,
        blur: 0,
        sepia: 0,
        grayscale: false,
      },
    },
  },
  work: {
    heroTitleLine1: 'DREAM',
    heroTitleLine2: 'SCAPES',
    heroSlash: '/',
    overviewTag: 'PROJECT OVERVIEW',
    overviewDescription:
      'An architectural visual monograph exploring concrete permanence and atmospheric transience across Kyoto and Reykjavik.',
    volumeTag: 'STILL STUDIO © 2026',
    volumeTitle: 'VOLUME ONE',
    heroImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=2600&q=98',
    heroPlateTitle: 'KYOTO REYKJAVIK DUALITY',
    titleTypography: {
      fontFamily: 'serif',
      fontWeight: '300',
      fontSizeScale: 1.0,
      letterSpacing: 'tight',
      textTransform: 'uppercase',
      textEffect: 'none',
      color: '#151515',
    },
    heroImageStyle: {
      scale: 1.0,
      aspectRatio: 'natural',
      borderRadius: 0,
      contrast: 100,
      brightness: 100,
      saturation: 100,
      blur: 0,
      sepia: 0,
      grayscale: false,
    },
  },
  project: {
    title: 'BLUEYARD',
    eyebrow: 'BRUTALIST VOID & LIGHTWELLS',
    locationYear: 'TOKYO, JAPAN — 2025',
    statementLine1: 'WHERE CONCRETE',
    statementLine2: 'HOLDS THE SILENCE.',
    narrativeBody:
      'A spatial inquiry into the quiet permanence of brutalist concrete forms, capturing how daylight carves depth into geometric voids.',
    primaryImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2000&q=98',
    secondaryImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&w=2600&q=98',
    titleTypography: {
      fontFamily: 'serif',
      fontWeight: '300',
      fontSizeScale: 1.0,
      letterSpacing: 'wide',
      textTransform: 'uppercase',
      textEffect: 'none',
      color: '#151515',
    },
    primaryImageStyle: {
      scale: 1.0,
      aspectRatio: 'natural',
      borderRadius: 0,
      contrast: 100,
      brightness: 100,
      saturation: 100,
      blur: 0,
      sepia: 0,
      grayscale: false,
    },
    secondaryImageStyle: {
      scale: 1.0,
      aspectRatio: 'natural',
      borderRadius: 0,
      contrast: 100,
      brightness: 100,
      saturation: 100,
      blur: 0,
      sepia: 0,
      grayscale: false,
    },
  },
  film: {
    hero: {
      topTag: 'Architectural Reliefs',
      topSub: 'Creative Direction & WebGL',
      subtitleItalic: 'The tactile nature of absence & spatial light.',
      badgeText: 'Continuous Bas-Relief Experience',
      mainTitleLine1: 'Innovative digital',
      mainTitleLine2: 'experiences studio',
      bottomNote: 'Selected Projects & Sound Design',
      heroPosterImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1400&q=80',
      titleTypography: {
        fontFamily: 'playfair',
        fontWeight: '400',
        fontSizeScale: 1.0,
        letterSpacing: 'normal',
        textTransform: 'none',
        textEffect: 'none',
        color: '#141414',
      },
      posterStyle: {
        scale: 1.0,
        aspectRatio: 'natural',
        borderRadius: 0,
        contrast: 100,
        brightness: 100,
        saturation: 100,
        blur: 0,
        sepia: 0,
        grayscale: false,
      },
    },
    projects: [
      {
        id: 'chronicles-of-light',
        title: 'Chronicles of Light',
        client: 'Maison Hermès',
        year: '2025',
        category: 'Digital Scenography & WebGL',
        tagline: 'An ephemeral virtual sanctuary exploring the tactile heritage of silk and luminescence.',
        coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1400&q=80',
        accentColor: '#D97706',
        featured: true,
      },
      {
        id: 'acoustic-monolith',
        title: 'Acoustic Monolith',
        client: 'Bang & Olufsen',
        year: '2024',
        category: 'Spatial Audio & Interactive Sculpture',
        tagline: 'Sculpting high-fidelity acoustic resonances into visible physical frequencies.',
        coverImage: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1400&q=80',
        accentColor: '#4F46E5',
        featured: true,
      },
      {
        id: 'kinetic-topography',
        title: 'Kinetic Topography',
        client: 'Aesop Worldwide',
        year: '2024',
        category: 'Generative Particle Simulation',
        tagline: 'An immersive digital distillation of botanical minerals and desert topography.',
        coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1400&q=80',
        accentColor: '#059669',
        featured: false,
      },
      {
        id: 'luminal-pavilion',
        title: 'Luminal Pavilion',
        client: 'Fondation Cartier',
        year: '2023',
        category: 'Virtual Exhibition & Archival Space',
        tagline: 'Reconstructing brutalist glass and cast-concrete architecture for global access.',
        coverImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1400&q=80',
        accentColor: '#DC2626',
        featured: false,
      },
    ],
  },
  krishna: {
    brandTitle: 'KRISHNA',
    brandSubtitle: 'PHOTOGRAPHY & VISUAL ARCHIVE',
    quote: 'Capturing moments that exist between time — shadows, geometry, and eternal soul.',
    titleTypography: {
      fontFamily: 'serif',
      fontWeight: '300',
      fontSizeScale: 1.0,
      letterSpacing: 'wide',
      textTransform: 'uppercase',
      textEffect: 'none',
      color: '#FFFFFF',
    },
    categories: [
      {
        key: 'monographs',
        label: 'MONOGRAPHS',
        num: '01',
        subtitle: 'Sacred Architecture & Brutal Voids',
        description: 'Large-scale fine art monographs studying stone, light, and architectural permanence across cultures.',
        quote: 'Forms emerge from darkness only when light touches their stillness.',
        heroImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=85',
      },
      {
        key: 'documentary',
        label: 'DOCUMENTARY',
        num: '02',
        subtitle: 'Sub-Arctic Geographies & Solitude',
        description: 'Field expeditions to isolated geological sanctuaries across Iceland, Patagonia, and northern Honshu.',
        quote: 'Silence is not empty; it is full of unhurried atmospheric weight.',
        heroImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=85',
      },
      {
        key: 'spaces',
        label: 'SPACES',
        num: '03',
        subtitle: 'Cast Concrete & Atmospheric Shadows',
        description: 'Interior spatial journeys through minimalist sanctuaries, lightwells, and Japanese tea pavilions.',
        quote: 'Space becomes sacred when shadows are allowed to inhabit it undisturbed.',
        heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85',
      },
      {
        key: 'portraits',
        label: 'PORTRAITS',
        num: '04',
        subtitle: 'Authentic Soul & Stillness',
        description: 'Intimate fine-art studio and environmental portraiture revealing the quiet intensity of character.',
        quote: 'In the stillness of a portrait, the soul steps forward without words.',
        heroImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1600&q=85',
      },
    ],
  },
  contactReviews: {
    studioName: 'APEX LIGHT',
    studioSubline: 'STUDIO ATELIER',
    email: 'atelier@stillstudio.co',
    phone: '+1 (800) 492-7489',
    address: 'Kyoto Sanctuary & New York Studio Atelier',
    location: 'PUNE, MAHARASHTRA, INDIA',
    atelierNote: 'Koregaon Park North • Available Worldwide for Commission',
    headline: 'CONTACT US.',
    description:
      'We welcome commissions across architectural spaces, editorial portraiture, and private client documentation. Tell us about your project or reach our atelier desk directly.',
    hours: 'Mon — Fri 09:00 — 18:00 JST / EST',
    titleTypography: {
      fontFamily: 'editorial',
      fontWeight: '400',
      fontSizeScale: 1.0,
      letterSpacing: 'tight',
      textTransform: 'uppercase',
      textEffect: 'none',
      color: '#111111',
    },
    categories: [
      {
        id: 'portrait',
        name: 'Portrait & Headshots',
        tagline: 'Studio lighting, creative bokeh & natural character portraits',
        basePrice: 14999,
        popular: true,
      },
      {
        id: 'wedding',
        name: 'Weddings & Elopements',
        tagline: 'Timeless cinematic coverage & intimate candid emotion',
        basePrice: 89999,
        popular: true,
      },
      {
        id: 'events',
        name: 'Editorial Events & Galas',
        tagline: 'Sophisticated documentary coverage for summits and cultural occasions',
        basePrice: 34999,
        popular: false,
      },
      {
        id: 'commercial',
        name: 'Commercial & Brand Campaigns',
        tagline: 'Architectural lookbooks, brand campaigns & advertising deliverables',
        basePrice: 59999,
        popular: false,
      },
      {
        id: 'fashion',
        name: 'Fashion & Lookbooks',
        tagline: 'Editorial high-fashion studio and location productions',
        basePrice: 44999,
        popular: false,
      },
      {
        id: 'realestate',
        name: 'Architectural & Interior Design',
        tagline: 'Ultra-wide angle spatial documentation and twilight elevation captures',
        basePrice: 24999,
        popular: false,
      },
      {
        id: 'drone',
        name: 'Aerial & Cinematic Drone',
        tagline: 'Licensed 4K drone cinematography and monumental landscape vistas',
        basePrice: 19999,
        popular: false,
      },
    ],
    addons: [
      {
        id: 'second_shooter',
        name: 'Second Master Photographer',
        price: 12000,
        description: 'Comprehensive dual-angle coverage for simultaneous scenes',
      },
      {
        id: 'rush_delivery',
        name: '48-Hour Priority Rush Mastering',
        price: 8000,
        description: 'Hand-retouched delivery turnaround within 48 hours',
      },
      {
        id: 'raw_files',
        name: 'Archival RAW Format Vault',
        price: 15000,
        description: 'Full uncompressed RAW files with perpetual commercial license',
      },
      {
        id: 'printed_album',
        name: 'Linen Bound Heirloom Fine Art Monograph',
        price: 25000,
        description: 'Artisanal Italian linen, heavy matte archival cotton paper',
      },
      {
        id: 'drone_addon',
        name: 'Supplemental Drone Horizon Flight',
        price: 9000,
        description: '60 minutes of licensed aerial coverage over property or venue',
      },
    ],
    reviews: [
      {
        id: 'rev-01',
        clientName: 'Aarav & Meera Singhania',
        roleOrTag: 'Wedding Commission · Udaipur Royal Palace',
        category: 'wedding',
        overallRating: 5,
        title: 'Breathtaking editorial poetry preserved for generations',
        reviewText:
          'Every photograph carries monumental weight and emotional intimacy. The lighting felt like a fine art exhibition rather than a standard wedding album. Our guests were mesmerized by the quiet dignity in each portrait.',
        favoriteDeliverable: 'Heirloom Linen Art Monograph & Golden Hour Twilight series',
        date: 'February 18, 2026',
        verifiedClient: true,
        helpfulCount: 38,
      },
      {
        id: 'rev-02',
        clientName: 'Devika Chawla',
        roleOrTag: 'Creative Director · Studio Kroma Fashion',
        category: 'fashion',
        overallRating: 5,
        title: 'Mastery over shadow, fabric texture, and atmospheric tension',
        reviewText:
          'Working with Still Studio was an absolute masterclass. The attention to skin tones, micro-contrast in fabrics, and medium format resolution exceeded our agency expectations. We booked our autumn campaign immediately.',
        favoriteDeliverable: 'Digital Medium Format 100MP Retouched Master Files',
        date: 'January 29, 2026',
        verifiedClient: true,
        helpfulCount: 24,
      },
      {
        id: 'rev-03',
        clientName: 'Vikramaditya Rao',
        roleOrTag: 'Principal Architect · Studio Vayu',
        category: 'realestate',
        overallRating: 5,
        title: 'Understands architectural silence and concrete volume like no other',
        reviewText:
          'Most photographers oversaturate and distort lines. Still Studio treated our concrete pavilion with reverence. The balance of brutalist geometry and soft morning light earned us a feature in Architectural Digest.',
        favoriteDeliverable: 'Twilight Perspective-Corrected Architectural Series',
        date: 'March 04, 2026',
        verifiedClient: true,
        helpfulCount: 19,
      },
      {
        id: 'rev-04',
        clientName: 'Rohan & Tara Kapoor',
        roleOrTag: 'Private Portrait Session · Studio Atelier',
        category: 'portrait',
        overallRating: 5,
        title: 'Felt like effortless friends capturing magic',
        reviewText:
          'We were anxious in front of studio cameras, but the subtle lighting and warm coaching put us right at ease within five minutes. The final portraits look like stills from a modern cinema film.',
        favoriteDeliverable: 'Warm 85mm prime portraits with soft natural falloff',
        date: 'April 14, 2026',
        verifiedClient: true,
        helpfulCount: 12,
      },
    ],
  },
};

export const PRESET_IMAGE_GALLERY = [
  {
    label: 'Kyoto Temple Dawn',
    category: 'Architecture',
    url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=2600&q=98',
  },
  {
    label: 'Tokyo Concrete Sanctuary',
    category: 'Architecture',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2000&q=98',
  },
  {
    label: 'Nordic Coastline Bastion',
    category: 'Landscape',
    url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&w=2600&q=98',
  },
  {
    label: 'Warm Analog Studio Light',
    category: 'Portrait',
    url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1600&q=85',
  },
  {
    label: 'Bas-Relief Minimalist Silk',
    category: 'Editorial',
    url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1400&q=80',
  },
  {
    label: 'Brutalist Monolith Shadows',
    category: 'Architecture',
    url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1400&q=80',
  },
  {
    label: 'Highland Mist & Basalt',
    category: 'Landscape',
    url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=85',
  },
  {
    label: 'Golden Hour Couple Intimacy',
    category: 'Wedding',
    url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=85',
  },
];
